### ISSUE TITLE
MDI CSS reloading at each page, and twice. MUST use CACHING

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictalk-frontend#117]
Find a way to cache CSS of Material Design Icons, and avoid reloading them each page. On lower devices it is a real hassle, has to be addressed

**Comment by UnlikelyBuddy1** [comment]
honestly I don't even know why it does this... Somehow i see no performance loss lately so let's close this issue and reopen it if there is a performance hit
