### ISSUE TITLE
Top bar: Surligner/Changer de couleurs lorsque l'on est dans la page

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictalk-frontend#174]
Quand on est dans la page "News", il faut que le bouton "News" soit mis en valeur pour indiquer que l'on y est

**Comment by UnlikelyBuddy1** [comment]
Nous on affiche même pas.... Genre si t'es dans tuto, tuto s'affiche pas vu que t'y est déjà. Donc ça rend cette upgrade useless
