### ISSUE TITLE
Refaire l'aspect des notifications

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictalk-frontend#178]
Mettre le nom de la collection en dessous de l'icône
Mettre le symbole user à côté du nom.
Mettre un mot pour l'action en plus du symbole

**Comment by UnlikelyBuddy1** [comment]
On a de la place horizontal mais peu vertical du coup jsp ... 
Le nom pour l'action c'est une bonne idée par contre
![image](https://user-images.githubusercontent.com/52712038/194966933-ad665239-fd8b-4362-8d75-b11235e4d4f5.png)

**Comment by UnlikelyBuddy1** [comment]
Enfaite faut mettre : 
"mailto (pavlos sidiras)" has "action" <br>
"img" _centered_ <br>
"label" _centered_

**Comment by UnlikelyBuddy1** [comment]
![image](https://user-images.githubusercontent.com/52712038/195070559-403a55da-98ee-45db-8116-c30b2e7b7b85.png)

Satisfying result
