### ISSUE TITLE
Simplification de l'écran Pictalk pour utilisateurs handicapés

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictalk-frontend#181]
Tout masquer dans la top bar sauf le bouton débloquer... Cela va moins perturber l'utilisateur handicapé et réduire les fausses manipulations de sa part

**Comment by UnlikelyBuddy1** [comment]
Est-ce que on ferait pas mieux de grisée plutôt ? parce que je crains que le "layout shift" sera trop gros si on le met en display: none

**Comment by UnlikelyBuddy1** [comment]
![firefox_611xKZBkDN](https://user-images.githubusercontent.com/52712038/196950197-34802167-fe94-4f62-9987-8cfb9fab82bf.png)
![firefox_ztqyujtr9W](https://user-images.githubusercontent.com/52712038/196950212-d0478e9f-aa60-47cf-82fd-55542cc13817.png)

peut-être faire un truc comme ça ?
