### ISSUE TITLE
Le logo pictalk ne devrait pas être intéractif

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictalk-frontend#183]
En mode accueil: Il revient à l'accueil.
En mode Pictalk: Il revient à Home & efface la phrase.

Un utilisateur débutant pourrait ne pas comprendre et perturber la compréhension de la picto bar

Action: Le rendre non-cliquable.

**Comment by UnlikelyBuddy1** [comment]
Le standard c'est quand même Logo = accueil. Je suis pas 100% convaincu
