### ISSUE TITLE
Drag and drop pictos and collections

### ISSUE THREAD

**Issue by UnlikelyBuddy1** [Pictalk-speech-made-easy/pictalk-frontend#188]
See if we can changes the places of pictos and send requests

**Comment by Ratatinator97** [comment]
Rules to follow:

- Cannot drag&drop in sidebar
- No drag&drop in user mode
- No drag&drop in admin mode without a key combination or long press of the picto/collection$
- Button to return to precedent (speech) when the picto/collection is being dragged

**Comment by Ratatinator97** [comment]
Questions:

Where to put the 'navigate back' button ? (Phone/tablet/computer)

When a collection should be draggable ? (Longclick, always on admin mode)

Should we highlight dropping zones ? (Other collections)

**Comment by UnlikelyBuddy1** [comment]
CSS style to add cross cursor when dragging object
``[draggable="true"] {
  cursor: move;
}``
