### ISSUE TITLE
Fix Admin mode, remove layout shift

### ISSUE THREAD

**Issue by UnlikelyBuddy1** [Pictalk-speech-made-easy/pictalk-frontend#203]
## How to fix
- Put the options sections on top of the image
- Make the white background transparent
- Make the buttons smaller, and fit at least 3
- Make just the arrow button in mobile mode, longpress to activate ?
- Reduce the time to go to admin, SOOOO LONG, OR make a full screen loading time
![pictoedit](https://user-images.githubusercontent.com/52712038/201543488-9a18e91d-cc18-4f70-b384-f150a054ce59.png)

**Comment by UnlikelyBuddy1** [comment]
- longpress on mobile, with 3 dots
- on top

**Comment by Ratatinator97** [comment]
#admin branch
