### ISSUE TITLE
Sharing menu: Add a recent share contact or favourite 

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictalk-frontend#205]
When sharing content to the same users, typing the email address again and again is a time cost.

- Add recent "shared" contacts
- Maybe add a favourite/sticky contacts

**Comment by UnlikelyBuddy1** [comment]
We can use an event handler of [@keydown](https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event) to search a match whenever the user types a new letter in the search box. Then we would need to store the recent contacts. I suggest storing those in a user field as a JSON ? 

Alternatively, we could make a small section with selectable users. I think it requires less time but, the other option is cooler.

**Comment by Ratatinator97** [comment]
Why shouldn't we store all contacts in a list ?

We could then easily show the last shared contacts and make some autocompletion/suggestion when typing

**Comment by UnlikelyBuddy1** [comment]
Another clever way would be to make another table. The problem with arrays in Postgres is that you don't get the benefit of added functionalities, e.g you cannot merge two arrays and specify that each value should be unique, you have to add one by one.
Whereas if we create a table, we can specify that each entry should be unique and do a bulk insertion 👍 

This approach should also be considered in the sharing process
