### ISSUE TITLE
Tutorial on TTS

### ISSUE THREAD

**Issue by UnlikelyBuddy1** [Pictalk-speech-made-easy/pictalk-frontend#234]
make a YouTube or/and written Tutorial about how to install new TTS for other languages or change male/female voice 

If we can, make a list of compatibility between OS - TSS language - Male/Female voice

**Comment by Ratatinator97** [comment]
Better use existing content in the internet.
I'm afraid it represents too much work for us to keep up to date such an article.

We could show some usefull links for some phone/tablet brands:

Samsung:
https://m.youtube.com/watch?v=zMlHMb_CX3I
https://m.youtube.com/watch?v=wwo34J55Dsc

Pixel/OnePlus ?:
https://support.google.com/accessibility/android/answer/6006983?hl=en

Apple:
https://support.apple.com/fr-fr/guide/iphone/iph96b214f0/ios

**Comment by UnlikelyBuddy1** [comment]
Or, but then we should find curated content. And include written tutorials if we can find some

**Comment by UnlikelyBuddy1** [comment]
merge into another issue
