### ISSUE TITLE
Firefox bug on TTS things, Tutorial & Recommend to install

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictalk-frontend#236]
1) No tts voice available for website language
2) Only male or female voices (Maybe)

**Comment by UnlikelyBuddy1** [comment]
Yeah, or just make a little info bubble saying :

"cannot find a voice ? take a look at this tutorial to install more"

**Comment by UnlikelyBuddy1** [comment]
make a YouTube or/and written Tutorial about how to install new TTS for other languages or change male/female voice

If we can, make a list of compatibility between OS - TSS language - Male/Female voice

Better use existing content in the internet.
I'm afraid it represents too much work for us to keep up to date such an article.

We could show some usefull links for some phone/tablet brands:

Samsung:
https://m.youtube.com/watch?v=zMlHMb_CX3I
https://m.youtube.com/watch?v=wwo34J55Dsc

Pixel/OnePlus ?:
https://support.google.com/accessibility/android/answer/6006983?hl=en

Apple:
https://support.apple.com/fr-fr/guide/iphone/iph96b214f0/ios

**Comment by Ratatinator97** [comment]
https://aulaabierta.arasaac.org/fr/communicateur-dynamique-asterics-grid-installation-de-voix-synthetiques-tts-sur-android
