### ISSUE TITLE
Export screenshot of collections

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictalk-frontend#246]
Bonjour, Est-il possible d'imprimer une catégorie créée, ce qui permettrait de faire des tableaux de langage assistés sans avoir besoin de tout recréer sur un autre logiciel ? Peut-on déplacer un pictogramme dans une catégorie ?

**Comment by UnlikelyBuddy1** [comment]
Use the browser included print feature. Or we could maybe make a quick canvas and draw the HTML in it

**Comment by UnlikelyBuddy1** [comment]
Probème => la feature de base du browser pour print la page n'est pas addapté et ne prend pas en compte le contenue scrollable (donc pas valable si la liste des pictogrammes dépasse 100vh)
Meilleur solution => Faire plusieurs screenshots
