### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictalk-frontend#248]
As the user base is growing, we need to estimate the max number of concurrent users that the server can actively use the app.

JMeter is an open source tool to load test APIs with advanced capabilities.

## We need to "simulate" real users
To do so, we develop some scenarios varying the kinds of usages possible.

### Scenario n°1: Get all images and collections+pictos

Difficulties: Have an array of "images paths" extracted from collection and pictogram requests in order to request to the API all the images.

**Comment by UnlikelyBuddy1** [comment]
Done with Jmeter, revealed some performance pitfalls. Follow up on backend repo
