### ISSUE TITLE
Make account creation easyer

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictalk-frontend#260]
Account creation isn't very clear. Most of people aren't used to < > arrows in order to navigate. They expect it to be automatic. We could maybe block the user from going back in the form after submiting + Pushing him to last step.
We could maybe make a link to verify the account instead of token copying.

**Comment by UnlikelyBuddy1** [comment]
I think the better move is to have a separated signup page
