### ISSUE TITLE
Dynamic PictoList rendering

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictalk-frontend#96]
Avec les dernières optimisation on est arrivés à ne pas re-render la liste trop fréquemment. 

Mais quand on modifie/ajoute/delete/copie on fait re-render toute la liste...
Il faudrait:
- faire un event pour passer la modification de la liste directement à la PictoList pour qu'elle delete/ajoute elle-même l'élément en question et ne pas re-render toute la liste

**Comment by UnlikelyBuddy1** [comment]
https://stackoverflow.com/questions/63714797/vue-reactivity-prevent-re-rendering-component-on-prop-update-with-input-v-model

**Comment by UnlikelyBuddy1** [comment]
This  worked for pictobar
https://stackoverflow.com/questions/63579468/change-specific-index-without-re-render-whole-array-in-vuejs
