### ISSUE TITLE
Optimize back-to-online full resync

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictalk-frontend#97]
With 2k pictograms it crashes hard :(

**Comment by UnlikelyBuddy1** [comment]
If we hash the result from GET collections we can see if something has changed and do nothing if the hash is the same

**Comment by UnlikelyBuddy1** [comment]
Done, we look at the last update date in the request response and compare it to the frontend local one, if they're the same then no update. if not found, add collection ;)
